#!/usr/bin/env python3
import sys
import os
from getpass import getuser
from subprocess import call, Popen
from wpgtk.wpg import *
import argparse

HOME = "/home/" + getuser()
WALLDIR = HOME + "/.wallpapers/"

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--set','-s', help='set the wallpaper and colorscheme', nargs='*')
    parser.add_argument('--add','-a', help='add images to the wallpaper folder and generate colorschemes', nargs='*')
    parser.add_argument('--list','-l', help='see which wallpapers are available', action='store_true')
    parser.add_argument('--version','-v', help='print the current version', action='store_true')
    parser.add_argument('--remove','-r', help='removes the wallpaper(s) from wallpaper folder', nargs='*')
    parser.add_argument('--current','-c', help='shows the current wallpaper', action='store_true')
    args = parser.parse_args()
    if len(sys.argv) < 2:
        run()

    if args.set:
        if len(args.set) == 1:
            try:
                os.system( 'wpcscript change ' + args.set[0] )
                execute_gcolorchange( args.set[0] )
                init_file = open( WALLDIR + 'wp_init.sh', 'w' )
                init_file.writelines( [ '#!/bin/bash\n', 'wpcscript change ' + args.set[0] + ' && ' ] )
                init_file.writelines( 'xrdb -merge ' + WALLDIR + '.' + args.set[0] +'.Xres' + '\n' )
                init_file.close()
                Popen( [ 'chmod', '+x', GLib.get_home_dir() + '/.wallpapers/wp_init.sh' ] )
            except TypeError:
                print( 'ERR:: file ' + args.set[0] + ' not found' )
        elif len(args.set) == 2:
            try:
                os.system( 'wpcscript change ' + args.set[0] )
                call( [ 'xrdb', '-merge', WALLDIR + '.' + args.set[1] + '.Xres'] )
                execute_gcolorchange( args.set[1] )
                init_file = open( WALLDIR + 'wp_init.sh', 'w' )
                init_file.writelines( [ '#!/bin/bash\n', 'wpcscript change ' + args.set[0] + ' && ' ] )
                init_file.writelines( 'xrdb -merge ' + WALLDIR + '.' + args.set[1] +'.Xres' + '\n' )
                init_file.close()
                Popen( [ 'chmod', '+x', GLib.get_home_dir() + '/.wallpapers/wp_init.sh' ] )
            except TypeError:
                print( 'ERR:: file  not found' )
        elif len( args.set ) > 2:
            print( 'ERR:: Specify just 2 filenames' )

    if args.list:
        os.system( 'wpcscript ls' )
    if args.version:
        print( 'current version: ' + version )
    if args.remove:
        for e in args.remove:
            call( [ 'wpcscript', 'rm', e ] )
            call( [ 'rm', WALLDIR + '.' + e + '.sample.png' ] )
    if args.current:
        os.system( 'wpcscript current' )
    if args.add:
        for e in args.add:
            call( [ 'wpcscript', 'add', e ] )
